# Cloudflare Workers Configuration
name = "demonslayer-billion-project"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Deployment settings
main = ".vercel/output/static/_worker.js/index.js"

[site]
bucket = ".vercel/output/static"
exclude = ["_worker.js", "_routes.json"]

[vars]
# Environment variables go here

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
