# Cloudflare Workers Configuration
name = "demonslayer-billion-project"
compatibility_date = "2024-08-17"
compatibility_flags = ["nodejs_compat"]

# Deployment settings
main = ".vercel/output/static/_worker.js/index.js"

[vars]
# Environment variables go here