# Cloudflare Workers Configuration
name = "demonslayer-billion-project"
compatibility_date = "2025-08-17"
compatibility_flags = ["nodejs_compat"]

# Deployment settings
main = ".vercel/output/static/_worker.js/index.js"
assets = { directory = ".vercel/output/static", binding = "ASSETS" }

[vars]
# Environment variables go here

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
